#define INPUT_KEY_UP KEY_W
#define INPUT_KEY_LEFT KEY_A
#define INPUT_KEY_DOWN KEY_S
#define INPUT_KEY_RIGHT KEY_D

#define INPUT_KEY_C_UP KEY_8
#define INPUT_KEY_C_LEFT KEY_U
#define INPUT_KEY_C_DOWN KEY_K
#define INPUT_KEY_C_RIGHT KEY_9

#define INPUT_KEY_A KEY_J
#define INPUT_KEY_B KEY_I
#define INPUT_KEY_X KEY_P
#define INPUT_KEY_Y KEY_LEFTBRACE
#define INPUT_KEY_Z KEY_SPACE
#define INPUT_KEY_L KEY_O
#define INPUT_KEY_R KEY_SEMICOLON

#define INPUT_KEY_MOD_X KEY_LEFTSHIFT
#define INPUT_KEY_MOD_Y KEY_RIGHTCTRL
#define INPUT_KEY_START KEY_ENTER
