[colors]
ansi = [
  "#141f1f",
  "#f85c7f",
  "#3fb563",
  "#f89950",
  "#7693f8",
  "#ad7bfa",
  "#25b29d",
  "#527a7a",
]
brights = [
  "#1f3030",
  "#fc8da0",
  "#54ef84",
  "#fac358",
  "#98b0fa",
  "#c19ffc",
  "#38ebd0",
  "#c2d6d6",
]
background = "#000000"
foreground = "#c2d6d6"
compose_cursor = "#f89950"
cursor_bg = "#c2d6d6"
cursor_border = "#c2d6d6"
cursor_fg = "#c2d6d6"
selection_bg = "#527a7a"
selection_fg = "#c2d6d6"
scrollbar_thumb = "#1f3030"
split = "#1f2e2e"
